on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses:  actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: |
              args: [--no-frozen-lockfile]

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
                  ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build --filter shared

      - name: Check for changes in shared
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/main...${{ github.sha }} -- shared)
          echo "::set-output name=changed_files::${CHANGED_FILES}"

      - name: Bump UI library version
        if: ${{ steps.check_changes.outputs.changed_files != '' }}
        id: bump_version
        run: |
          cd shared

          # Obtener la versión actual
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Versión actual: $CURRENT_VERSION"

          # Incrementar la versión
          npm version patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "Nueva versión: $NEW_VERSION"

          # Volver al directorio raíz del monorepo
          cd ../..

          # Actualizar el archivo package.json del monorepo con la nueva versión
          sed -i "s/\"shared\/ui\": \"^$CURRENT_VERSION\"/\"shared\": \"^$NEW_VERSION\"/" package.json

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump version to ${{ steps.version.outputs.new_version }}"

